
# trigger.yaml
# Sample config for Trigger
# Modify and place in /etc/trigger/

trigger_environment: "cloud or k8s (on-premise)" 

triggers:
  - event: "pod_restart"
    identifier: "podname"        
    action: "action or triggerbook"  

  - event: "cron"
    identifier: "infra_component"  
    action: "action/triggerbook"  

